version: '3.8'

services:

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: catty_reminders
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    image: ghcr.io/tyty-land/catty-reminders-app:latest
    restart: unless-stopped
    ports:
      - "8181:8181"
    depends_on:
      - db

volumes:
  db_data:
