serverAddr = "course.prafdin.ru"
serverPort = 7000

auth.method = "token"
auth.token = "devops"

[[proxies]]
name = "hook-shankin"
type = "http"
localPort = 8080
customDomains = ["webhook.shankin.course.prafdin.ru"]

[[proxies]]
name = "app-shankin"
type = "http"
localPort = 8181
customDomains = ["app.shankin.course.prafdin.ru"]

#SSH
[[proxies]]
name = "ssh-shankin"
type = "tcp"
localPort = 22
remotePort = 3131
