name: CD Pipeline

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH (Docker)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: course.prafdin.ru
          port: 3131
          username: ubu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          commend_timeout: 20m
          script: |
            cd /home/ubu/app-code
            git fetch origin --tags
            git reset --hard ${{ github.ref_name }}

            docker compose down || true
            docker compose pull web
            docker compose up -d
