name: CD Pipeline

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH (Docker)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: course.prafdin.ru
          port: 3131
          username: ubu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop catty-app || true
            docker rm catty-app || true
            
            
            docker pull ghcr.io/tyty-land/catty-reminders-app:latest
            
            docker run -d \
              -p 8181:8181 \
              --name catty-app \
              --restart always \
              -e DEPLOY_REF=${{ github.sha }} \
              ghcr.io/tyty-land/catty-reminders-app:latest
